/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package XMLCreator;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.w3c.dom.Attr;
import org.w3c.dom.DOMImplementation;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.Text;

/**
 *
 * @author ROOT
 */
public class XMLCreator extends javax.swing.JFrame {

    /**
     * Creates new form XMLCreator
     */
    public XMLCreator() {
        initComponents();
    }
    ArrayList<String> nombre = new ArrayList<>();
    ArrayList<String> apellido = new ArrayList<>();
    ArrayList<String> telefono = new ArrayList<>();
    ArrayList<String> genero = new ArrayList<>();
    String ruta;
    int numero_Persona;
    int datos = 0;
    boolean control_fichero = false;
    FileReader fr = null;
    FileWriter fw = null;
    BufferedReader br = null;
    BufferedWriter bw = null;
    String raiz1 ="<agenda>"; 
    String raiz2 ="</agenda>"; 
    
     private static String PillarExtension(String file) {
        
        if(file.lastIndexOf(".") != -1 && file.lastIndexOf(".") != 0)
        return file.substring(file.lastIndexOf(".")+1);
        else return "";
    }
     
     protected void GenerarXML() throws TransformerConfigurationException, TransformerException, IOException{
       try{
         br =new BufferedReader(new FileReader(this.ruta));
         bw = new BufferedWriter(new FileWriter(this.ruta));
         
          //Pasa por cada linea de ArrayList y lo guarda en br y muestra por pantalla
          bw.write(this.raiz1);
          bw.newLine();
          for (int x=0;x<numero_Persona;x++){
              bw.write("\t <persona genero=\""+genero.get(x)+"\">");
              bw.newLine();
              bw.write ("\t \t <nombre>"+nombre.get(x)+"</nombre>");
              bw.newLine();
              bw.write ("\t \t <apellido>"+apellido.get(x)+"</apellido>");
              bw.newLine();
              bw.write ("\t \t <telefono>"+telefono.get(x)+"</telefono>");
              bw.newLine();
              bw.write ("\t </persona>");
              bw.newLine();
          }
          bw.write(this.raiz2);
         //Limpiamos la arrayList para que no se almacene
         nombre.clear();
         apellido.clear();
         genero.clear();
         telefono.clear();
         }catch (IOException e) {
          System.out.println("S'ha trobat un error llegint el fitxer especificat: "+e.getMessage());
       } finally {
          if (null!=br) {
             br.close();
             bw.close();
          }
         }
     }
     
     private void Reset(){
        textField_Datos_Nombre.setText("");
        textField_Datos_Apellido.setText("");
        textField_Datos_Telefono.setText("");
        checkBox_Datos_Genero_Hombre.setSelected(false);
        checkBox_Datos_Genero_Mujer.setSelected(false);
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelRuta = new javax.swing.JPanel();
        textfieldRuta = new javax.swing.JTextField();
        buttonRuta_Cargar = new javax.swing.JButton();
        panelOpciones = new javax.swing.JPanel();
        buttonOpciones_Generar = new javax.swing.JButton();
        buttonOpciones_Siguiente = new javax.swing.JButton();
        label_Opciones_NumPer = new javax.swing.JLabel();
        textField_Opciones_NumPer = new javax.swing.JTextField();
        buttonOpciones_Empezar = new javax.swing.JButton();
        panel_Datos = new javax.swing.JPanel();
        label_Datos_Nombre = new javax.swing.JLabel();
        textField_Datos_Nombre = new javax.swing.JTextField();
        label_Datos_Apellido = new javax.swing.JLabel();
        textField_Datos_Apellido = new javax.swing.JTextField();
        label_Datos_Telefono = new javax.swing.JLabel();
        textField_Datos_Telefono = new javax.swing.JTextField();
        label_Datos_genero = new javax.swing.JLabel();
        checkBox_Datos_Genero_Hombre = new javax.swing.JCheckBox();
        checkBox_Datos_Genero_Mujer = new javax.swing.JCheckBox();
        panel_Info = new javax.swing.JPanel();
        label_Info = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CIDE XML CREATOR");
        setResizable(false);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelRuta.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "SELECCIONA LA RUTA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        textfieldRuta.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        buttonRuta_Cargar.setText("CARGAR");
        buttonRuta_Cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRuta_CargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRutaLayout = new javax.swing.GroupLayout(panelRuta);
        panelRuta.setLayout(panelRutaLayout);
        panelRutaLayout.setHorizontalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textfieldRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRuta_Cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRutaLayout.setVerticalGroup(
            panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRutaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRutaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfieldRuta)
                    .addComponent(buttonRuta_Cargar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelOpciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "OPCIONES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        buttonOpciones_Generar.setText("GENERAR");
        buttonOpciones_Generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpciones_GenerarActionPerformed(evt);
            }
        });

        buttonOpciones_Siguiente.setText("SIGUIENTE");
        buttonOpciones_Siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpciones_SiguienteActionPerformed(evt);
            }
        });

        label_Opciones_NumPer.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        label_Opciones_NumPer.setText("NºPERSONAS:");

        textField_Opciones_NumPer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textField_Opciones_NumPer.setText("0");

        buttonOpciones_Empezar.setText("EMPEZAR");
        buttonOpciones_Empezar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOpciones_EmpezarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Opciones_NumPer, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField_Opciones_NumPer, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonOpciones_Generar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonOpciones_Empezar)
                .addGap(18, 18, 18)
                .addComponent(buttonOpciones_Siguiente)
                .addGap(26, 26, 26))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGroup(panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(label_Opciones_NumPer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textField_Opciones_NumPer)
                    .addComponent(buttonOpciones_Generar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpciones_Siguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOpciones_Empezar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel_Datos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "INTRODUCE LOS DATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label_Datos_Nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_Datos_Nombre.setText("NOMBRE");

        textField_Datos_Nombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label_Datos_Apellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_Datos_Apellido.setText("APELLIDO");

        textField_Datos_Apellido.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label_Datos_Telefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_Datos_Telefono.setText("TELEFONO");

        textField_Datos_Telefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        label_Datos_genero.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        label_Datos_genero.setText("GENERO");

        checkBox_Datos_Genero_Hombre.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkBox_Datos_Genero_Hombre.setText("HOMBRE");
        checkBox_Datos_Genero_Hombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_Datos_Genero_HombreActionPerformed(evt);
            }
        });

        checkBox_Datos_Genero_Mujer.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        checkBox_Datos_Genero_Mujer.setText("MUJER");
        checkBox_Datos_Genero_Mujer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBox_Datos_Genero_MujerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_DatosLayout = new javax.swing.GroupLayout(panel_Datos);
        panel_Datos.setLayout(panel_DatosLayout);
        panel_DatosLayout.setHorizontalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Datos_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Datos_Apellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Datos_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label_Datos_genero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(textField_Datos_Telefono, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                        .addComponent(textField_Datos_Apellido)
                        .addComponent(textField_Datos_Nombre))
                    .addGroup(panel_DatosLayout.createSequentialGroup()
                        .addComponent(checkBox_Datos_Genero_Hombre)
                        .addGap(18, 18, 18)
                        .addComponent(checkBox_Datos_Genero_Mujer)))
                .addGap(52, 52, 52))
        );
        panel_DatosLayout.setVerticalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Datos_Nombre)
                    .addComponent(textField_Datos_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Datos_Apellido)
                    .addComponent(textField_Datos_Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_Datos_Telefono)
                    .addComponent(textField_Datos_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkBox_Datos_Genero_Mujer, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkBox_Datos_Genero_Hombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_Datos_genero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Info.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "INFORMACIÓN", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        label_Info.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N

        javax.swing.GroupLayout panel_InfoLayout = new javax.swing.GroupLayout(panel_Info);
        panel_Info.setLayout(panel_InfoLayout);
        panel_InfoLayout.setHorizontalGroup(
            panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panel_InfoLayout.setVerticalGroup(
            panel_InfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_InfoLayout.createSequentialGroup()
                .addComponent(label_Info, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_Datos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRuta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_Info, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOpciones_GenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpciones_GenerarActionPerformed
        // Resetea los texfield y checkbox de la seccion datos
        if (numero_Persona == datos){
            try {
                GenerarXML();
            } catch (TransformerException ex) {
                Logger.getLogger(XMLCreator.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(XMLCreator.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        } else{
        label_Info.setText("ERROR: El numero de datos introducido no coincide con el numero de personas indicadas");
        nombre.clear();
        apellido.clear();
        telefono.clear();
        genero.clear();
        }
    }//GEN-LAST:event_buttonOpciones_GenerarActionPerformed

    private void checkBox_Datos_Genero_HombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_Datos_Genero_HombreActionPerformed
        // Desmarca la opcion de hombre
        checkBox_Datos_Genero_Mujer.setSelected(false);
    }//GEN-LAST:event_checkBox_Datos_Genero_HombreActionPerformed

    private void checkBox_Datos_Genero_MujerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBox_Datos_Genero_MujerActionPerformed
        //Desmarca la opcion de mujer
        checkBox_Datos_Genero_Hombre.setSelected(false);
    }//GEN-LAST:event_checkBox_Datos_Genero_MujerActionPerformed

    private void buttonRuta_CargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRuta_CargarActionPerformed
        // TODO add your handling code here:
        if (PillarExtension(textfieldRuta.getText()).equals("xml")){
         this.ruta = textfieldRuta.getText();
         label_Info.setText("Ruta introducida correctamente");
        } else{
            label_Info.setText("ERROR: La ruta no pertenece a un documento XML");
        }
    }//GEN-LAST:event_buttonRuta_CargarActionPerformed

    private void buttonOpciones_EmpezarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpciones_EmpezarActionPerformed
        // TODO add your handling code here:
        this.numero_Persona = Integer.parseInt(textField_Opciones_NumPer.getText());
        if (this.ruta == null){
            label_Info.setText("ERROR: Primero hay que introducir la ruta");
        } else{
            label_Info.setText("Fichero listo para introducir datos");
            this.control_fichero=true;
        }
        
    }//GEN-LAST:event_buttonOpciones_EmpezarActionPerformed

    private void buttonOpciones_SiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOpciones_SiguienteActionPerformed
        // TODO add your handling code here:
        if(this.control_fichero && datos<numero_Persona){
        nombre.add(textField_Datos_Nombre.getText());
        apellido.add(textField_Datos_Apellido.getText());
        telefono.add(textField_Datos_Telefono.getText());
        if (checkBox_Datos_Genero_Hombre.isSelected()){
            genero.add("Hombre");
        }
        if (checkBox_Datos_Genero_Mujer.isSelected()){
            genero.add("Mujer");
        }
        datos++;
        Reset();
        label_Info.setText(datos+" de "+numero_Persona+" Rellenad@s");
        } else {
            label_Info.setText("ERROR: No se ha empezado la generacion del documento para poder introducir datos");
        }
        
    }//GEN-LAST:event_buttonOpciones_SiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(XMLCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(XMLCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(XMLCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(XMLCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new XMLCreator().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonOpciones_Empezar;
    private javax.swing.JButton buttonOpciones_Generar;
    private javax.swing.JButton buttonOpciones_Siguiente;
    private javax.swing.JButton buttonRuta_Cargar;
    private javax.swing.JCheckBox checkBox_Datos_Genero_Hombre;
    private javax.swing.JCheckBox checkBox_Datos_Genero_Mujer;
    private javax.swing.JLabel label_Datos_Apellido;
    private javax.swing.JLabel label_Datos_Nombre;
    private javax.swing.JLabel label_Datos_Telefono;
    private javax.swing.JLabel label_Datos_genero;
    private javax.swing.JLabel label_Info;
    private javax.swing.JLabel label_Opciones_NumPer;
    private javax.swing.JPanel panelOpciones;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelRuta;
    private javax.swing.JPanel panel_Datos;
    private javax.swing.JPanel panel_Info;
    private javax.swing.JTextField textField_Datos_Apellido;
    private javax.swing.JTextField textField_Datos_Nombre;
    private javax.swing.JTextField textField_Datos_Telefono;
    private javax.swing.JTextField textField_Opciones_NumPer;
    private javax.swing.JTextField textfieldRuta;
    // End of variables declaration//GEN-END:variables
}
