/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;

/**
 *
 * @author ROOT
 */
public class Calculadora extends javax.swing.JFrame {

    /**
     * Creates new form Calculadora
     */
    
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelgeneral = new javax.swing.JPanel();
        panelresultados = new javax.swing.JPanel();
        resultado1 = new javax.swing.JLabel();
        resultado2 = new javax.swing.JLabel();
        resultadooperador = new javax.swing.JLabel();
        valor2 = new javax.swing.JButton();
        valor1 = new javax.swing.JButton();
        valor3 = new javax.swing.JButton();
        valor4 = new javax.swing.JButton();
        valor6 = new javax.swing.JButton();
        valor5 = new javax.swing.JButton();
        valor7 = new javax.swing.JButton();
        valor9 = new javax.swing.JButton();
        valor8 = new javax.swing.JButton();
        valorresta = new javax.swing.JButton();
        valorsuma = new javax.swing.JButton();
        valormult = new javax.swing.JButton();
        valorce = new javax.swing.JButton();
        valorexit = new javax.swing.JButton();
        valorc = new javax.swing.JButton();
        valor0 = new javax.swing.JButton();
        valorigual = new javax.swing.JButton();
        valorpunto = new javax.swing.JButton();
        valordivision = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULADORA");
        setResizable(false);

        panelgeneral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelresultados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        resultado1.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        resultado1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resultado2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        resultado2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        resultadooperador.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resultadooperador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelresultadosLayout = new javax.swing.GroupLayout(panelresultados);
        panelresultados.setLayout(panelresultadosLayout);
        panelresultadosLayout.setHorizontalGroup(
            panelresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelresultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultado2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultadooperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelresultadosLayout.setVerticalGroup(
            panelresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelresultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelresultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado2, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(resultado1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultadooperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        valor2.setText("2");
        valor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor2ActionPerformed(evt);
            }
        });

        valor1.setText("1");
        valor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor1ActionPerformed(evt);
            }
        });

        valor3.setText("3");
        valor3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor3ActionPerformed(evt);
            }
        });

        valor4.setText("4");
        valor4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor4ActionPerformed(evt);
            }
        });

        valor6.setText("6");
        valor6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor6ActionPerformed(evt);
            }
        });

        valor5.setText("5");
        valor5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor5ActionPerformed(evt);
            }
        });

        valor7.setText("7");
        valor7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor7ActionPerformed(evt);
            }
        });

        valor9.setText("9");
        valor9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor9ActionPerformed(evt);
            }
        });

        valor8.setText("8");
        valor8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor8ActionPerformed(evt);
            }
        });

        valorresta.setText("-");
        valorresta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorrestaActionPerformed(evt);
            }
        });

        valorsuma.setText("+");
        valorsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorsumaActionPerformed(evt);
            }
        });

        valormult.setText("*");
        valormult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valormultActionPerformed(evt);
            }
        });

        valorce.setText("CE");
        valorce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorceActionPerformed(evt);
            }
        });

        valorexit.setText("Exit");
        valorexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorexitActionPerformed(evt);
            }
        });

        valorc.setText("C");
        valorc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorcActionPerformed(evt);
            }
        });

        valor0.setText("0");
        valor0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valor0ActionPerformed(evt);
            }
        });

        valorigual.setText("=");
        valorigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorigualActionPerformed(evt);
            }
        });

        valorpunto.setText(".");
        valorpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorpuntoActionPerformed(evt);
            }
        });

        valordivision.setText("/");
        valordivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valordivisionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelgeneralLayout = new javax.swing.GroupLayout(panelgeneral);
        panelgeneral.setLayout(panelgeneralLayout);
        panelgeneralLayout.setHorizontalGroup(
            panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgeneralLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelgeneralLayout.createSequentialGroup()
                        .addComponent(valor4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valor5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valor6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorresta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelgeneralLayout.createSequentialGroup()
                        .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valorce, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelgeneralLayout.createSequentialGroup()
                        .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelgeneralLayout.createSequentialGroup()
                                .addComponent(valor7, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valor8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(valor0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelgeneralLayout.createSequentialGroup()
                                .addComponent(valor9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valormult, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelgeneralLayout.createSequentialGroup()
                                .addComponent(valorpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(valordivision, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(valorexit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valorigual, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelresultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        panelgeneralLayout.setVerticalGroup(
            panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelgeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelresultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorsuma, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorce, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorresta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor7, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valor9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valormult, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorigual, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelgeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valor0, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorexit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valorpunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valordivision, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelgeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelgeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void valor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor2ActionPerformed
        // Boton de valor 2
       resultado1.setText(resultado1.getText()+"2");
    }//GEN-LAST:event_valor2ActionPerformed

    private void valor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor1ActionPerformed
        // Boton de valor 1
      resultado1.setText(resultado1.getText()+"1");
    }//GEN-LAST:event_valor1ActionPerformed

    private void valor3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor3ActionPerformed
        // Boton de valor 3
        resultado1.setText(resultado1.getText()+"3");
    }//GEN-LAST:event_valor3ActionPerformed

    private void valor4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor4ActionPerformed
        // Boton de valor 4
        resultado1.setText(resultado1.getText()+"4");
    }//GEN-LAST:event_valor4ActionPerformed

    private void valor6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor6ActionPerformed
        // Boton de valor 6
        resultado1.setText(resultado1.getText()+"6");
    }//GEN-LAST:event_valor6ActionPerformed

    private void valor5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor5ActionPerformed
        // Boton de valor 5
        resultado1.setText(resultado1.getText()+"5");
    }//GEN-LAST:event_valor5ActionPerformed

    private void valor7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor7ActionPerformed
        // Boton de valor 7
        resultado1.setText(resultado1.getText()+"7");
    }//GEN-LAST:event_valor7ActionPerformed

    private void valor9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor9ActionPerformed
        // Boton de valor 9
        resultado1.setText(resultado1.getText()+"9");
    }//GEN-LAST:event_valor9ActionPerformed

    private void valor8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor8ActionPerformed
        // Boton de valor 8
        resultado1.setText(resultado1.getText()+"8");
    }//GEN-LAST:event_valor8ActionPerformed

    private void valorrestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorrestaActionPerformed
        // Boton Valor Resta 
        resultado2.setText(resultado1.getText());
        resultado1.setText("");
        resultadooperador.setText("-");
    }//GEN-LAST:event_valorrestaActionPerformed

    private void valorsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorsumaActionPerformed
        // Boton de sumar
        resultado2.setText(resultado1.getText());
        resultado1.setText("");
        resultadooperador.setText("+");
    }//GEN-LAST:event_valorsumaActionPerformed

    private void valormultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valormultActionPerformed
        // Boton de multiplicar
        resultado2.setText(resultado1.getText());
        resultado1.setText("");
        resultadooperador.setText("*");
    }//GEN-LAST:event_valormultActionPerformed

    private void valorceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorceActionPerformed
        // Boton de valor CE
        resultado1.setText("");
        resultado2.setText("");
        resultadooperador.setText("");
    }//GEN-LAST:event_valorceActionPerformed

    private void valorexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorexitActionPerformed
        // Boton de salir
        System.exit(0);
    }//GEN-LAST:event_valorexitActionPerformed

    private void valorcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorcActionPerformed
        // Boton de Valor C
        resultado1.setText("");
    }//GEN-LAST:event_valorcActionPerformed

    private void valor0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valor0ActionPerformed
        // Boton de valor 0
        resultado1.setText(resultado1.getText()+"0");
    }//GEN-LAST:event_valor0ActionPerformed

    private void valorigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorigualActionPerformed
        //Metodo que se encarga de calcular detectado la operacion mediante un bucle if
        double result = 0;
        
        if (resultadooperador.getText()== "+"){
          result = Double.parseDouble(resultado2.getText()) +  Double.parseDouble(resultado1.getText());
        } else if (resultadooperador.getText()== "-"){
          result = Double.parseDouble(resultado2.getText()) -  Double.parseDouble(resultado1.getText());
        } else if (resultadooperador.getText()== "*"){
          result = Double.parseDouble(resultado2.getText()) *  Double.parseDouble(resultado1.getText());
        } else if (resultadooperador.getText()== "/"){
             result = Double.parseDouble(resultado2.getText()) /  Double.parseDouble(resultado1.getText());
        } else {
          result = 0;
        }
        
        String resultado = Double.toString(result);
        resultado2.setText("");
        resultadooperador.setText("");
        resultado1.setText(resultado);
    }//GEN-LAST:event_valorigualActionPerformed

    private void valorpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorpuntoActionPerformed
        // TODO add your handling code here:
        resultado1.setText(resultado1.getText()+".");
    }//GEN-LAST:event_valorpuntoActionPerformed

    private void valordivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valordivisionActionPerformed
        // TODO add your handling code here:
        resultado2.setText(resultado1.getText());
        resultado1.setText("");
        resultadooperador.setText("/");
    }//GEN-LAST:event_valordivisionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelgeneral;
    private javax.swing.JPanel panelresultados;
    private javax.swing.JLabel resultado1;
    private javax.swing.JLabel resultado2;
    private javax.swing.JLabel resultadooperador;
    private javax.swing.JButton valor0;
    private javax.swing.JButton valor1;
    private javax.swing.JButton valor2;
    private javax.swing.JButton valor3;
    private javax.swing.JButton valor4;
    private javax.swing.JButton valor5;
    private javax.swing.JButton valor6;
    private javax.swing.JButton valor7;
    private javax.swing.JButton valor8;
    private javax.swing.JButton valor9;
    private javax.swing.JButton valorc;
    private javax.swing.JButton valorce;
    private javax.swing.JButton valordivision;
    private javax.swing.JButton valorexit;
    private javax.swing.JButton valorigual;
    private javax.swing.JButton valormult;
    private javax.swing.JButton valorpunto;
    private javax.swing.JButton valorresta;
    private javax.swing.JButton valorsuma;
    // End of variables declaration//GEN-END:variables
}
